Support optional arguments on Integrated-devnet
Shard-Labs/starknet-hardhat-plugin pull request #122
Opened 2022-06-15 07:21 UTC by Nathan-SL

- Support optional arguments on integrated-devnet

## Usage related changes
- Optional arguments can now be passed in `integratedDevnet` 
```json
integratedDevnet: {
    url: "http://127.0.0.1:5050",
    venv: "active",
    args: ["--lite-mode"]
}
```
## Development related changes
- 

## Checklist:

- [x] I have formatted the code
- [x] I have performed a self-review of the code
- [x] I have rebased to the base branch
- [x] I have documented the changes
- [x] I have updated the tests
- [ ] I have created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example).

2022-06-17 09:52 UTC, FabijanC requested changes
Document this in README.md in the integrated-devnet section (it was expected to be so if the documentation check in the PR description says so). You can just update the hardhat.config sample there with a line and a comment; you can use the same args that you used in the test.

2022-06-17 09:52 UTC, FabijanC commented on src/devnet/docker-devnet.ts
> +        return  spawn("docker", args);
Rerun prettify

2022-06-17 10:21 UTC, Nathan-SL commented on src/devnet/docker-devnet.ts
> +        return  spawn("docker", args);
https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/122/commits/b45e5111813159db53cc8d84f1dca17ef44d4851

2022-06-17 10:42 UTC, FabijanC approved these changes
Approving; the tests are failing but should be fixed with 0.9.0 support (blocked by #124).

2022-06-20 09:38 UTC, FabijanC commented
Blocked by #124

2022-06-27 16:37 UTC, merged