state: add dump/load timeout and wait until dump has finished
Shard-Labs/starknet-hardhat-plugin pull request #168
Opened 2022-07-15 14:10 UTC by RedFox20

## Usage related changes

-   If underlying server dies, the timeouts will make sure the plugin does not freeze
-   It checks correctly until dump file has finished writing, otherwise immediate load would cause everything to explode

## Development related changes

-   

## Checklist:

-   [ ] Formatted the code
-   [ ] No linter errors
-   [ ] Tried to avoid introducing linter warnings
-   [ ] Performed a self-review of the code
-   [ ] Rebased to the last commit of the target branch (or merged it into my branch)
-   [ ] Documented the changes
-   [ ] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.sh`)
-   [ ] Linked issues which this PR resolves
-   [ ] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
    -   < EXAMPLE_REPO_PR_URL > 
    -   [ ] Modified `test.sh` to use my example repo branch
    -   [ ] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

2022-07-15 14:26 UTC, FabijanC commented
Can you go through the checklist in your PR description? For this PR, you can ignore the last two points: about the example repo PR and the tests passing.

2022-07-15 14:27 UTC, FabijanC commented
Also, have you seen this: https://github.com/Shard-Labs/starknet-hardhat-plugin/issues/167
Is the timeout applicable only for dump/load?

2022-07-16 10:08 UTC, RedFox20 commented
> Also, have you seen this: #167 Is the timeout applicable only for dump/load?
I would implement it in another PR just as #167 describes. Generally adding thin wrappers is better for long term maintenance and bugfixes, so an utility makes perfect sense.

2022-07-18 10:28 UTC, FabijanC requested changes

2022-07-18 10:28 UTC, FabijanC commented on src/devnet-utils.ts
> +            if (!fs.existsSync(path)) {
What if someone is running their devnet in a different environment, e.g. a container or something remote? This check should be added server-side.

2022-07-18 10:28 UTC, FabijanC commented on src/devnet-utils.ts
> +                { timeout: 20000 } // timeout is required because the server can die
Can you extract this 20000? It's used multiple times.

2022-07-18 10:28 UTC, FabijanC commented on src/devnet-utils.ts
> +    async waitUntilSaveFinished(path:string): Promise<void> {
Have you run the formatter on this code?

2022-08-08 16:10 UTC, merged