Voyager contract verification
Shard-Labs/starknet-hardhat-plugin pull request #25
Opened 2021-12-03 15:58 UTC by dribeiro-ShardLabs

2021-12-03 16:15 UTC, FabijanC commented on test/starknet-verify/hardhat.config.ts
> +        starknetArtifacts: "my-starknet-artifacts"
why not just use the default starknetArtifacts path? like in the `plain` test case

2021-12-03 16:16 UTC, FabijanC commented on test/with-wait/hardhat.config.ts
> +        starknetSources: "my-starknet-sources"
why not just use the default starknetSources?

2021-12-03 16:20 UTC, FabijanC commented on src/index.ts
> +        await axios.get(voyagerUrl,{
Why use both await and callbacks?
How about this:
```typescript
const resp = await axios.get(url, args);
const data = resp.data;
```
Or something like this: https://github.com/axios/axios#typescript

2021-12-03 16:23 UTC, FabijanC commented on src/index.ts
> +        if(isVerified)
Should the user be notified about contract already having been verified?
Also indent the return statement and put it in curly braces.

2021-12-03 16:36 UTC, FabijanC commented on src/index.ts
> +        if(args.wait){      //  If the "wait" flag was passed as an argument, check the previously stored transaction hashes for their statuses
Ok, probably not until we do the refactor which will remove the recursion.

2021-12-03 16:41 UTC, FabijanC commented on src/index.ts
> +            .then(response => {
In case you stick with callbacks, this `response` is unused.

2021-12-03 16:42 UTC, FabijanC commented on src/index.ts
> +        if(args.starknetNetwork && args.starknetNetwork !== ALPHA){
Could you make this if-else branching clearer?

2021-12-03 16:43 UTC, FabijanC commented on src/index.ts
> +            while(!done){   // Run loop until all transactions are PENDING or ACCEPTED
This action of the starknet-verify task is quiet big. Some of its sections should be extracted to separate functions.

2021-12-03 16:45 UTC, FabijanC commented on package-lock.json
>  {
Perhaps this is a matter of npm version you're using, but it'd be the best if we both use a version that generates a package-lock.json with lockfileVersion 2.

2021-12-06 09:09 UTC, FabijanC requested changes
The new changes seem to cover my comments from the last review, except the required changes to package-lock.json: https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/25#discussion_r762091241

2021-12-06 09:39 UTC, FabijanC approved these changes

2021-12-06 12:01 UTC, Tiago-shardlabs approved these changes

2021-12-06 13:22 UTC, FabijanC requested changes

2021-12-06 13:22 UTC, FabijanC commented on src/types.ts
> +import { Console } from "console";
This line is probably accidentally here.

2021-12-06 13:22 UTC, FabijanC commented on src/index.ts
> +                    txHashes.push(executed.stdout.toString().match(".*Transaction hash: (?<tx_hash>\\w*).*").groups["tx_hash"]);
I guess you didn't want this line to look the way it does. Perhaps you meant to indent it and enclose with curly braces. Also, would it be possible to utilize `extractTxHash` from types.ts?

2021-12-06 13:22 UTC, FabijanC commented on src/index.ts
> +import { DockerWrapper, StarknetWrapper, VenvWrapper } from "./starknet-wrappers";
`StarknetWrapper` is not explicitly used.

2021-12-06 14:01 UTC, FabijanC approved these changes

2021-12-06 17:04 UTC, merged