290 Tests in docker
Shard-Labs/starknet-hardhat-plugin pull request #296
Opened 2023-01-21 22:30 UTC by shramee

## Usage related changes

- Users are unaffected.

## Development related changes

#### Executing tests in docker

You can use docker tester image. The image includes testing environment set up with everything required to run the tests. The spawned container has access to docker daemon so it can also run the tests that require spawning Devnet/Cairo CLI etc containers.

```
npm run docker-tester
```

This is take you in the container shell. Once in the container, you can use the `test-` scripts defined in `package.json` in an isolated environment.

Fixes #290

## Checklist:

-   [x] Formatted the code
-   [x] No linter errors + tried to avoid introducing linter warnings
-   [x] Performed a self-review of the code
-   [x] Rebased to the last commit of the target branch (or merged it into my branch)
-   [x] Documented the changes
-   [x] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.ts`)
-   [x] Linked issues which this PR resolves
-   [ ] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
    -   < EXAMPLE_REPO_PR_URL > 
    -   [ ] Modified `test.sh` to use my example repo branch
    -   [ ] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

2023-01-22 07:02 UTC, shramee commented
Sorry, this needs more testing.

2023-02-23 07:19 UTC, shramee commented
Add a ton of docs, let me know if it's a bit much and some of it is unnecessary...

--------------------------

## Dockerized testing environment

We have added a Docker in Docker, called DinD, setup to run the tests that need to use Docker from within a Docker container.
This allows running tests easily without changing your development environment. Read about running tests in [Executing tests in docker](#executing-tests-in-docker) section. If you are not adding **Docker container volumes** you can skip this section.

Running tests inside DinD requires some additional setup/parsing when adding new Docker container volumes to map container paths.

### Adding new docker container

If you are adding a new docker container with volumes please refer to the next section, [Adding volumes to a docker container](#adding-volumes-to-a-docker-container), to properly parse host paths for Docker in Docker to work.

### Adding volumes to a docker container

For volume mounts, Use `getVolumeHostPathFilter` function from `./external-server/external-server` to get the filter function to prepare paths for DinD if required.

Here's an example,

```js
// import ...
import { getVolumeHostPathFilter } from "./external-server/external-server";

// A bunch of code...

const volumeHostPathFilter = getVolumeHostPathFilter();
// Docker volume mounting args
const volumes = [
    "-v",
    `${volumeHostPathFilter(pathInHost)}:${pathInContainer}`,
    "-v",
    `${volumeHostPathFilter(pathInHost2)}:${pathInContainer2}`
];

// Other bunch of code...
```

We get the filter function from `getVolumeHostPathFilter()`. Then `host` parts for every volume are passed filtered with `volumeHostPathFilter` function.

## Testing

### ...

### Executing tests in docker

You can use docker tester image. The image includes testing environment set up with everything required to run the tests. The spawned container has access to docker daemon so it can also run the tests that require spawning Devnet/Cairo CLI etc containers. Read more in [Dockerized testing environment](#dockerized-testing-environment) section.

```
npm run docker-tester
```

This is take you in the container shell. Once in the container, you can use the `test-` scripts defined in `package.json` in an isolated environment.

### ...

2023-02-23 07:31 UTC, shramee commented on scripts/ensure-python.sh
> +    which "/opt/circleci/.pyenv/versions/$PY_VERSION/bin/python" || pyenv install "$PY_VERSION" -s
`-s` flag skips if `pyenv` version is already installed.
https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-install
>  -s/--skip-existing    Skip the installation if the version appears to be installed already

2023-02-23 07:32 UTC, shramee commented on scripts/install-devnet.sh
> +STARKNET_DEVNET_DEFAULT=$(node -e "console.log(require('../config.json').STARKNET_DEVNET)")
Sets default for `STARKNET_DEVNET` env var from `config.json`

2023-02-23 07:36 UTC, shramee commented on scripts/install-devnet.sh
> +pip3 install "starknet-devnet==${STARKNET_DEVNET:=$STARKNET_DEVNET_DEFAULT}" | { grep --invert-match 'Requirement already satisfied:' || :; }
1. Uses STARKNET_DEVNET_DEFAULT fallback
2. grep removes `Requirement already satisfied` logs.
3. `|| :;` part, which is like `or nothing;`, prevents grep from `exit`ing the process.

2023-02-23 07:37 UTC, shramee commented on scripts/setup-venv.sh
> +    CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip3 install fastecdsa  | { grep --invert-match 'Requirement already satisfied:' || :; }
Same as https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/296/files#r1115318562
Strips `Requirement already satisfied` logs and stops grep from exiting the process.

2023-02-23 07:38 UTC, shramee commented on scripts/test.sh
> +if [[ "${CIRCLE_BRANCH:=}" == "master" ]] && [[ "$EXAMPLE_REPO_BRANCH" != "plugin" ]]; then
Empty default from `CIRCLE_BRANCH`

2023-03-03 09:40 UTC, FabijanC requested changes
Your PRs seems to introduce changes that are already on master. Perhaps merging master into your branch would help (also there are conflicts with the target branch). It should be easier to review after that.

I haven't fully reviewed, but if I understand correctly, some parts of the coding (non-testing code) are now working differently just to enable testing with DinD?

2023-03-06 11:24 UTC, shramee commented
Closed in favour of #331

2023-03-06 11:24 UTC, closed without merging